import os
import json
import glob
import re
from django.db import models
from django.core.management.base import BaseCommand
from django.core.files import File
from rapidfuzz import process, utils


# ⚠️ CHANGE THIS to your actual app name!
from products.models import Product, Customer, MicaComponent, CaseComponent

# ANSI Color Codes for terminal highlighting
class Colors:
    WARNING = '\033[93m' # Yellow
    GREEN = '\033[92m'   # Green
    CYAN = '\033[96m'    # Cyan
    RESET = '\033[0m'    # Reset

def split_dims(dim_string):
    """Splits a string like '454 x 1051' into H, W, D."""
    if not dim_string:
        return "", "", ""
    # Split by 'x', 'X', or '*'
    parts = [p.strip() for p in re.split(r'[xX\*]', dim_string)]
    h = parts[0] if len(parts) > 0 else ""
    w = parts[1] if len(parts) > 1 else ""
    d = parts[2] if len(parts) > 2 else ""
    return h, w, d

class Command(BaseCommand):
    help = 'Imports OCR JSON data into the Django database safely.'

    def update_field(self, obj, field_name, new_val, label):
        """Updates a field and prints the change in the terminal."""
        if not new_val:
            return # Don't overwrite with blanks

        old_val = getattr(obj, field_name)

        # If the new value is different from the old value
        if str(old_val) != str(new_val) and new_val != "":
            setattr(obj, field_name, new_val)
            if old_val:
                # HIGHLIGHT: Overwriting existing data
                print(f"{Colors.WARNING}  ⚠️  [CHANGED] {label}: '{old_val}' ➔ '{new_val}'{Colors.RESET}")
            else:
                # NEW: Adding data to an empty field
                print(f"{Colors.GREEN}  ✅  [NEW] {label}: '{new_val}'{Colors.RESET}")
        else:
            # UNCHANGED: It matched perfectly
            print(f"  ➖  [OK] {label}: '{old_val}' (No change)")

    def handle(self, *args, **kwargs):
        # Find all JSON files generated by your OCR script
        json_files = glob.glob(os.path.join(settings.MEDIA_ROOT, "scan_inbox", "ocr_json", "*.json"))
        json_files += glob.glob(os.path.join(settings.MEDIA_ROOT, "scan_inbox", "review", "*.json"))
        
        if not json_files:
            self.stdout.write(self.style.ERROR("No JSON files found in ocr_snippets/"))
            return

        for json_path in json_files:
            with open(json_path, 'r') as f:
                data = json.load(f)

            r_number = data.get("r_number", "").upper()
            front = data.get("front", {})
            rear = data.get("rear", {})

            if not r_number:
                print(f"{Colors.WARNING}Skipping {json_path} - No R-Number found.{Colors.RESET}")
                continue

            print(f"\n{Colors.CYAN}=========================================={Colors.RESET}")
            print(f"{Colors.CYAN} PROCESSING RECORD: {r_number}{Colors.RESET}")
            print(f"{Colors.CYAN}=========================================={Colors.RESET}")

            # 1. GET OR CREATE PRODUCT
            # We check both r_number and legacy_r_number just to be safe
            product = Product.objects.filter(models.Q(r_number=r_number) | models.Q(legacy_r_number=r_number)).first()

            if not product:
                print(f"{Colors.GREEN}🌟 Creating Brand New Product for {r_number}{Colors.RESET}")
                # Create with the required unique r_number
                product = Product(r_number=r_number, legacy_r_number=r_number)
            else:
                print(f"{Colors.WARNING}🔍 Found Existing Product. Auditing differences...{Colors.RESET}")

            # Update Basic Product Fields
            self.update_field(product, 'legacy_r_number', front.get('legacy_r_number'), 'Legacy R-Number')
            self.update_field(product, 'voltage', front.get('voltage'), 'Voltage')
            self.update_field(product, 'wattage', front.get('wattage'), 'Wattage')
            self.update_field(product, 'die_shape', front.get('die_shape'), 'Die Shape')
            self.update_field(product, 'element_type', front.get('element_type'), 'Element Type')
            self.update_field(product, 'turns_apart', front.get('turns_apart'), 'Turns Apart')
            self.update_field(product, 'description_private', rear.get('description_private'), 'Rear Notes')

            # Optional: Match Customer by Name
            # 1. Grab the name from the OCR data first!
            company_name = front.get("company_name", "").strip()

            # 2. Now check if we actually found a name to match
            if company_name:
                # Get all customer names from the DB as a list
                all_customers = {c.company_name: c for c in Customer.objects.all()}
                customer_names = list(all_customers.keys())

                # Find the best match (Fuzzy Match)
                result = process.extractOne(
                    company_name,
                    customer_names,
                    processor=utils.default_process
                )

                if result and result[1] >= 70:
                    matched_name = result[0]
                    score = result[1]
                    cust = all_customers[matched_name]

                    print(f"{Colors.GREEN}  ✅  [FUZZY MATCH] '{company_name}' ➔ '{matched_name}' ({int(score)}% match){Colors.RESET}")

                    if not product.pk or not product.customers.filter(id=cust.id).exists():
                        product.save()
                        product.customers.add(cust)
                else:
                    # Added a safe check here in case result is None
                    guess = result[0] if result else "None"
                    pct = int(result[1]) if result else 0
                    print(f"{Colors.WARNING}  ⚠️  [NO MATCH] Best guess was '{guess}' at {pct}% - check DB!{Colors.RESET}")

            product.save()

            # 2. GET OR CREATE MICA COMPONENT
            mica, _ = MicaComponent.objects.get_or_create(product=product)
            print(f"\n{Colors.CYAN}--- MICA SPECS ---{Colors.RESET}")
            self.update_field(mica, 'core_quantity', front.get('mica_core_qty'), 'Core Qty')
            self.update_field(mica, 'cover_quantity', front.get('mica_cover_qty'), 'Cover Qty')
            self.update_field(mica, 'loading_ohms', front.get('mica_loading_ohms'), 'Ohms')
            self.update_field(mica, 'wire_type', front.get('mica_wire_type'), 'Wire Type')

            # Split Combined Dimensions
            core_h, core_w, core_d = split_dims(front.get('mica_core_h_mica_core_w_mica_core_d'))
            self.update_field(mica, 'core_dim_h', core_h, 'Core Dim H')
            self.update_field(mica, 'core_dim_w', core_w, 'Core Dim W')

            cover_h, cover_w, cover_d = split_dims(front.get('mica_cover_h_mica_cover_w_mica_cover_d'))
            self.update_field(mica, 'cover_dim_h', cover_h, 'Cover Dim H')
            self.update_field(mica, 'cover_dim_w', cover_w, 'Cover Dim W')
            mica.save()

            # 3. GET OR CREATE CASE COMPONENT
            case, _ = CaseComponent.objects.get_or_create(product=product)
            print(f"\n{Colors.CYAN}--- CASE SPECS ---{Colors.RESET}")
            self.update_field(case, 'wire_grade', front.get('case_wire_grade'), 'Wire Grade')

            # Split Combined Dimensions
            in_h, in_w, in_d = split_dims(front.get('case_inner_h_case_inner_w_case_inner_d'))
            self.update_field(case, 'inner_dim_h', in_h, 'Inner Dim H')
            self.update_field(case, 'inner_dim_w', in_w, 'Inner Dim W')

            out_h, out_w, out_d = split_dims(front.get('case_outer_h_case_outer_w_case_outer_d'))
            self.update_field(case, 'outer_dim_h', out_h, 'Outer Dim H')
            self.update_field(case, 'outer_dim_w', out_w, 'Outer Dim W')

            sh_h, sh_w, sh_d = split_dims(front.get('case_sheath_h_case_sheath_w_case_sheath_d'))
            self.update_field(case, 'sheath_dim_h', sh_h, 'Sheath Dim H')
            self.update_field(case, 'sheath_dim_w', sh_w, 'Sheath Dim W')
            case.save()

            # 4. ATTACH THE PICTORIAL DIAGRAM
            diagram_path = f"ocr_snippets/{data.get('r_number', 'R_TEST_001')}/front/pictoral_diagram.jpg"
            if os.path.exists(diagram_path) and not product.pictorial_diagram:
                with open(diagram_path, 'rb') as f:
                    # Save it directly into the Django ImageField
                    product.pictorial_diagram.save(f"{r_number}_diagram.jpg", File(f), save=True)
                print(f"{Colors.GREEN}  🖼️  [IMAGE SAVED] Pictorial Diagram attached!{Colors.RESET}")

        print(f"\n{Colors.CYAN}=========================================={Colors.RESET}")
        print(f"{Colors.GREEN}✅ Database Import Complete!{Colors.RESET}")