# Generated by Django 5.1.3 on 2026-03-18 08:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_number",
                    models.CharField(
                        help_text="e.g., C000000", max_length=50, unique=True
                    ),
                ),
                ("company_name", models.CharField(max_length=200, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{8,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{8,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("suburb", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NSW", "New South Wales"),
                            ("VIC", "Victoria"),
                            ("QLD", "Queensland"),
                            ("ACT", "Australian Capital Territory"),
                            ("TAS", "Tasmania"),
                            ("SA", "South Australia"),
                            ("WA", "Western Australia"),
                            ("NT", "Northern Territory"),
                        ],
                        default="NSW",
                        max_length=3,
                    ),
                ),
                ("postcode", models.CharField(blank=True, max_length=4, null=True)),
                ("rep_name", models.CharField(blank=True, max_length=100, null=True)),
                ("rep_email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "rep_phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{8,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal staff notes", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["customer_number"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. SCB, MICA, TUB", max_length=15, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Strip Ceramic Band", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Product Categories",
            },
        ),
        migrations.CreateModel(
            name="PortalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_principal",
                    models.BooleanField(
                        default=False,
                        help_text="Can manage other users for this company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_users",
                        to="products.customer",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "r_number",
                    models.CharField(
                        help_text="e.g., R1111 or R00001", max_length=50, unique=True
                    ),
                ),
                (
                    "plug_type",
                    models.CharField(
                        blank=True,
                        help_text="Type to search or add a new plug on the fly.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "voltage",
                    models.CharField(help_text="e.g., 240 or 240/415", max_length=50),
                ),
                ("wattage", models.CharField(max_length=50)),
                (
                    "dim_h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Height in mm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "dim_w",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Width in mm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "dim_d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Depth in mm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "description_invoice",
                    models.TextField(
                        help_text="Customer view (visible on portal/invoice)"
                    ),
                ),
                (
                    "description_private",
                    models.TextField(
                        blank=True,
                        help_text="Internal fabrication details (hidden from customer)",
                        null=True,
                    ),
                ),
                (
                    "turns_apart",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="in mm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("other_notes", models.TextField(blank=True, null=True)),
                (
                    "customers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Can be assigned to multiple branches/companies.",
                        related_name="products",
                        to="products.customer",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Select the heater type.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.productcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["r_number"],
            },
        ),
        migrations.CreateModel(
            name="MicaComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover_dim_h",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "cover_dim_w",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "cover_dim_d",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("cover_quantity", models.IntegerField(default=1)),
                (
                    "core_dim_h",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "core_dim_w",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "core_dim_d",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("core_quantity", models.IntegerField(default=1)),
                (
                    "loading_ohms",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "wire_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Ni80, British Standard",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="mica_drawings/"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mica_details",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_number",
                    models.CharField(
                        help_text="Legacy 5-digit or new 6-digit number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_PROD", "In Production"),
                            ("QC", "Quality Check"),
                            ("DISPATCHED", "Dispatched"),
                            ("INVOICED", "Invoiced"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("order_quantity", models.IntegerField(default=1)),
                ("requested_date", models.DateField(auto_now_add=True)),
                ("required_date", models.DateField(blank=True, null=True)),
                ("dispatched_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_order",
                    models.CharField(
                        blank=True,
                        help_text="Customer PO number",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "ordered_for_customer",
                    models.ForeignKey(
                        help_text="Permanently locks this invoice to the branch that ordered it.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historical_jobs",
                        to="products.customer",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_date"],
            },
        ),
        migrations.CreateModel(
            name="CaseComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inner_dim_h",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "inner_dim_w",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "inner_dim_d",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "outer_dim_h",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "outer_dim_w",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "outer_dim_d",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "sheath_dim_h",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "sheath_dim_w",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "sheath_dim_d",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("wire_grade", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="case_drawings/"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_details",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("MICA_DRAWING", "Mica Drawing"),
                            ("CASE_DRAWING", "Case Drawing"),
                            ("PHOTO", "Photo"),
                            ("SCAN", "Scanned Legacy File"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="product_files/%Y/%m/")),
                ("label", models.CharField(blank=True, max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="products.product",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
