# Generated by Django 5.1.3 on 2026-03-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="dim_d",
        ),
        migrations.RemoveField(
            model_name="product",
            name="dim_h",
        ),
        migrations.RemoveField(
            model_name="product",
            name="dim_w",
        ),
        migrations.AddField(
            model_name="product",
            name="die_shape",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Die Press / Tooling Shape",
            ),
        ),
    ]
