# Generated by Django 6.0.3 on 2026-03-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_dim_d_remove_product_dim_h_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="legacy_r_number",
            field=models.CharField(
                blank=True, help_text="Old system R-Number", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="company_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
