# Generated by Django 5.1.3 on 2026-03-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_legacy_r_number_alter_customer_company_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={"ordering": ["name"], "verbose_name_plural": "Product Categories"},
        ),
    ]
