# Generated by Django 5.1.3 on 2026-03-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_productcategory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="postcode",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
