# Generated by Django 5.1.3 on 2026-03-24 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_customer_postcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casecomponent",
            name="image",
        ),
        migrations.RemoveField(
            model_name="job",
            name="dispatched_date",
        ),
        migrations.RemoveField(
            model_name="job",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="job",
            name="required_date",
        ),
        migrations.RemoveField(
            model_name="micacomponent",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="element_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="front_card_scan",
            field=models.ImageField(
                blank=True, null=True, upload_to="card_scans/front/"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pictorial_diagram",
            field=models.ImageField(blank=True, null=True, upload_to="diagrams/"),
        ),
        migrations.AddField(
            model_name="product",
            name="private_notes",
            field=models.TextField(
                blank=True, help_text="OCR result from rear card notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rear_card_scan",
            field=models.ImageField(
                blank=True, null=True, upload_to="card_scans/rear/"
            ),
        ),
        migrations.AlterField(
            model_name="casecomponent",
            name="inner_dim_d",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="casecomponent",
            name="inner_dim_h",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="casecomponent",
            name="inner_dim_w",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="casecomponent",
            name="outer_dim_d",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="casecomponent",
            name="outer_dim_h",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="casecomponent",
            name="outer_dim_w",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="casecomponent",
            name="sheath_dim_d",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="casecomponent",
            name="sheath_dim_h",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="casecomponent",
            name="sheath_dim_w",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="postcode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="ordered_for_customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="historical_jobs",
                to="products.customer",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="purchase_order",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="micacomponent",
            name="core_dim_d",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="micacomponent",
            name="core_dim_h",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="micacomponent",
            name="core_dim_w",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="micacomponent",
            name="core_quantity",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="micacomponent",
            name="cover_dim_d",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="micacomponent",
            name="cover_dim_h",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="micacomponent",
            name="cover_dim_w",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="micacomponent",
            name="cover_quantity",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="micacomponent",
            name="loading_ohms",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="micacomponent",
            name="wire_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="portalprofile",
            name="is_principal",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.productcategory",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="customers",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.customer"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_invoice",
            field=models.TextField(
                blank=True, help_text="Visible on portal/invoice", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_private",
            field=models.TextField(
                blank=True, help_text="Internal fabrication details", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="plug_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="turns_apart",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="voltage",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="wattage",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
